logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  port: 8080
  forward-headers-strategy: native

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=1d
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        show_sql: true
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        id:
          new_generator_mappings: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: validate
        default_schema: ${SPRING_DATASOURCE_SCHEMA}
  flyway:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    serialization:
      indent_output: true
      fail-on-self-references: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api-docs/api
  swagger-ui:
    path: /api-docs/api.html
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    oauth:
      client-id: app
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}/protocol/openid-connect/auth
    tokenUrl: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    audience: geofer
    issuer: ${INFO_APP_ISSUER}
    version: '@project.version@'
