enum PermType {
  CONNECT="CONNECT",
  CREATE="CREATE",
  DELETE="DELETE",
  EXECUTE="EXECUTE",
  INSERT="INSERT",
  REFERENCES="REFERENCES",
  SELECT="SELECT",
  TEMPORARY="TEMPORARY",
  TRIGGER="TRIGGER",
  TRUNCATE="TRUNCATE",
  UPDATE="UPDATE",
  USAGE="USAGE"
}
  
export default PermType;